baseURL = "https://hugo-test.c3re.de/"
languageCode = "en-us"
title = "c3RE"
theme = "hugo-theme-flat"
# themeDir = '../..'
defaultContentLanguage = "de"
relativeURLs = true
style = "green"


[params]
mainSections = ["."]

[[menus.main]]
name = "Philosophie"
url = "/unsere-philosophie"
[[menus.main]]
name = "Codeweek"
url = "/codeweek"




[[menus.main]]
name = "Werkzeuge"
url = "https://dienste.c3re.de"
weight = 90

[[menus.main]]
name = "Downloads"
url = "/downloads/"
weight = 110

# Footer Menue
[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Kontakt"
url = "/kontakt"

[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Impressum"
url = "/impressum"

[[params.footer_rows.items]]
name = "Datenschutzerklärung"
url = "/datenschutz"

