baseURL = "https://www.c3re.de"
languageCode = "de-de"
title = "c3RE"
theme = "hugo-theme-flat"
defaultContentLanguage = "de"
relativeURLs = true
style = "green"


[params]
mainSections = ["."]

[pagination]
pagerSize = 4

[[menus.main]]
name = "Philosophie"
url = "/unsere-philosophie"

[[menus.main]]
name = "Codeweek"
url = "/codeweek"

# [[menus.main]]
# name = "News"
# url = "/news/"
# weight = 80

[[menus.main]]
name = "Werkzeuge"
url = "https://dienste.c3re.de/"
weight = 90

[[menus.main]]
name = "Downloads"
url = "/downloads/"
weight = 110
[[menus.main]]
name = "Vorbeikommen"
url = "/kontakt/"
weight = 110

# Footer Menue
[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Kontakt"
url = "/kontakt"

#[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Impressum"
url = "/impressum"

[[params.footer_rows.items]]
name = "Datenschutzerklärung"
url = "/datenschutz"

[[params.footer_rows.items]]
name = "Mitglied werden"
url = "https://wiki.c3re.de/de/Chaostreff-Hackerhuette-c3RE/Mitgliedwerden"

[[params.footer_rows]]
[[params.footer_rows.items]]
pre ="FRIENDS & FAMILY"
[[params.footer_rows.items]]
name ="Blumenthal 7 e.V."
url="https://www.blumenthal7.de/"
[[params.footer_rows.items]]
name ="Freifunk Emscherland"
url="https://freifunk-emscherland.de/"
[[params.footer_rows.items]]
name ="Linux User Group Marl"
url="https://www.lug-marl.de/"
